HOHQ Mesh import
HorribleSanity/Raven.jl pull request #64
Opened 2023-09-17 18:40 UTC by masonamccallum

Closes #39 
## Summary
Here we allow the user to import a mesh generated with HOHQ. The file format must be set in HOHQ to be ABAQUS which is not the default. Once HOHQ has generated the .inp file we can then import with the following interface.

`coarse_grid = coarsegrid("out/IceCreamCone.inp")`

New interface showcased in: examples/grids/hohqmeshimport.jl

2023-09-19 22:39 UTC, lcw requested changes
This is great!  Would it be possible to add a test of the curved mesh stuff?

2023-09-19 22:39 UTC, lcw commented on Project.toml
> +HOHQMesh = "e4f4c7b8-17cb-445a-93c5-f69190ed6c8c"
`HOHQMesh` is only used in the examples and not Raven.  I suggest we move this to `examples/grids/Project.toml`

2023-09-19 22:39 UTC, lcw commented on examples/grids/hohqmeshimport.jl
> +# Alternativly one could import directly from an existing control file.
```suggestion
# Alternatively one could import directly from an existing control file.
```

2023-09-19 22:39 UTC, lcw commented on src/Raven.jl
> +export AbaqusMeshImport
```suggestion
```

This type is not used outside of Raven so let's hold off from exporting it.

2023-09-19 22:39 UTC, lcw commented on src/Raven.jl
> +
```suggestion
```
see above

2023-09-19 22:39 UTC, lcw commented on src/coarsegrids.jl
> +    @assert R > r "R (outter radius) must be greater that r (inner radius)"
```suggestion
    @assert R > r "R (outer radius) must be greater that r (inner radius)"
```

2023-09-19 22:39 UTC, lcw commented on src/lobattocells.jl
> +        w[i] = 1.0 / w[i]
```suggestion
        w[i] = 1 / w[i]
```

We don't want to use `Float64` literals because it will promote `Float32`s.

2023-09-19 22:39 UTC, lcw commented on src/lobattocells.jl
> +                f1x, f1y, f1z = 0.25 * (p1 * (1 - r) * (1 - t) + p2 * (r + 1) * (1 - t) + p5 * (1 - r) * (t + 1) + p6 * (r + 1) * (t + 1))
We don't want to use `Float64` literals because it will promote `Float32`s.

2023-09-22 18:57 UTC, masonamccallum commented
Great! Thanks for the feedback. Ill add some tests.

2023-09-23 20:41 UTC, masonamccallum commented
I added a failing test and fixed problem in the next commit.

2023-09-28 17:57 UTC, lcw commented
Looks great!  I just pushed a couple of minor changes.  If things pass I'll merge it later today.

2023-09-29 16:54 UTC, lcw approved these changes

2023-09-29 16:55 UTC, merged